FROM metwork/mfcom-centos7-buildimage

RUN echo -e "[metwork_{{BRANCH_NAME}}]\n\
name=Metwork Continuous Integration Branch {{BRANCH_NAME}}\n\
baseurl=http://metwork-framework.org/pub/metwork/continuous_integration/rpms/{{BRANCH_NAME}}/centos7/\n\
gpgcheck=0\n\
enabled=1\n\
metadata_expire=0\n" >/etc/yum.repos.d/metwork.repo

RUN yum -y install metwork-mfcom
